### DEFAULT ROUTE
GET http://localhost:3000/

### FETCH SONGS REQUEST
GET http://localhost:3000/songs


### Find Songs Request
GET http://localhost:3000/songs/1

### Create new song
POST http://localhost:3000/songs
Content-Type: application/json

{
    "title":"Lasting Forever",
    "artists": ["Sigla","Nsengi"],
    "releasedDate": "2022-09-29",
    "duration":"02:34"
}

### Update song 
PUT http://localhost:3000/songs/1

### Delete song request
DELETE  http://localhost:3000/songs/1